services:
  storage:
    image: docker.io/valkey/valkey:9.0.1
    container_name: storage
    ports:
      - "6379:6379"
    networks:
      - valkey
    volumes:
      - storage-data:/var/lib/postgresql/data
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - go-cache:/go
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - storage
    networks:
      - valkey
    environment:
      - TZ=Europe/Paris
      - VALKEY_HOST=storage
      - VALKEY_PORT=6379
      - BASE_URL=http://127.0.0.1:8080
networks:
  valkey:
    driver: bridge

volumes:
  storage-data:
  go-cache:
